# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gravity
email: epg@ad.unc.edu
description: The ErinGray19 Jekyll Theme
baseurl: "" # the subpath of your site, e.g. /blog
url: https://eringray19.github.io/
twitter_username: nope
github_username:  ErinGray19

# Build settings
markdown: kramdown
